### ISSUE TITLE
Phone number formats

### ISSUE THREAD

**Issue by ciamalaeaskan** [joshswan/react-native-autolink#51] opened 2020-11-16 10:44 UTC
Hi i have phone number's of different countries. but it has hyperlinked for (XXX) XXX-XXXX this format only. Where we should change condition for this ?

**Comment by joshswan** [comment] 2020-11-16 19:49
Duplicate of #25. Definitely an enhancement that needs more exploring; I just haven't had the time to dig into it yet.

You can see the regex that [Autolinker.js](https://github.com/gregjacobs/Autolinker.js/blob/master/src/matcher/phone-matcher.ts) is using under the hood for phone number matching. Either expanding the support for international phone numbers over there, or bypassing Autolinker and creating a set of regexes in this package would be required.

I'm open to either option. If you have specific regexes for certain countries, drop them into #25.

**Closed by joshswan** 2020-11-16 19:49 UTC
