### ISSUE TITLE
Text from custom matcher become invisible after several renders on Android.

### ISSUE THREAD

**Issue by andrew-golik** [joshswan/react-native-autolink#75] opened 2023-10-28 22:09 UTC
Hello!

I highlight searched text wrapped in `em` tag. At first it is all rendered good when matcher works swaping tag with text within. But when I out from search mode and change text to normal (without wrapped text fragments) all text most likely become invisible.  Sometimes not but it very seldom case. Why invisible - it save place, and it is not mess with styles (I changed colors for text and background).

![Screenshot_1](https://github.com/joshswan/react-native-autolink/assets/130767173/acba8fbf-877a-45b5-87ab-0064406feb81)

Such problem is only for Android (emulator 9, device 9, emulator 12). iPhone 7 has not this problem.
RN 0.63.5.
react-native-autolink 4.2.0 (4.1.0 also).

```
{item.attributes.content ? (
  <Text
    style={[
      styles.textMessage,
      item.attributes.own
        ? styles.myTextMessage
        : styles.consultantTextMessage,
    ]}
  >
    <Autolink
      text={item.attributes.content}
      linkStyle={item.attributes.own ? styles.uriOwn : styles.uri}
      onLongPress={onCopyMessage}
      matchers={[
        {
          pattern: /<em>.*?<\/em>/gm,
          style: item.attributes.own
            ? isCurrentSearchIndex
              ? styles.searchedTextOwn
              : styles.searchedTextOwnCurrent
            : isCurrentSearchIndex
            ? styles.searchedText
            : styles.searchedTextCurrent,
          onPress: () => {},
          onLongPress: () => {},
          getLinkText: (replacerArgs) =>
            ' ' + replacerArgs[0].slice(4, -5) + ' ',
        },
      ]}
    />
  </Text>
) : null}
```

PS: I wanted to place yet another issue about disable touchability of Text elem in matcher using `disabled` or `accessibilityState={{disabled: true}}` or remove `onPress` prop by condition, but found [such issue](https://github.com/joshswan/react-native-autolink/issues/70) in closed, where you advice use `renderLink`. I tried it now and problem is gone (for my case, of course). So you can close issue if it is not important for you.

**Comment by joshswan** [comment] 2023-10-28 23:10
Hm, this is tough to diagnose without a reproducible example. I certainly haven't seen such behavior on any of our apps running in production, but we don't have anything below RN 0.70 anymore. Perhaps it's related to the old RN and OS versions you mentioned 🤷‍♂️. Or it could be something specific to your implementation

Regarding your later point, custom matchers also take a `renderLink` option now if you want to do something custom for those, per #73.

Going to close this for now since you said you found a workaround, but will reopen if there's more reports or a way to reproduce.

**Closed as completed by joshswan** 2023-10-28 23:10 UTC

**Comment by andrew-golik** [comment] 2023-10-28 23:30
Thanks, I used it renderLink specifically for matcher, did not pay attention that it appear in last version only and even did not read docs .  Just try and it worked. :) There are plans about update RN version for that project so it will bе interesting try to reproduce bug with fresh RN.

**Comment by Qy742698** [comment] 2024-07-03 06:30
How do I use the matchers property?
